version: '3.8'

services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    restart: always

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app
    networks:
      - app-network
    restart: always


networks:
  app-network:
    driver: bridge
