repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        files: ^back/app/.*\.py$
      - id: end-of-file-fixer
        files: ^back/app/.*\.py$
      - id: check-yaml
        files: ^back/app/.*\.yaml$
      - id: check-added-large-files
        files: ^back/app/.*

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        files: ^back/app/.*\.py$

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        files: ^back/app/.*\.py$
        args: [--config=back/.flake8]
