FROM python:3.9-slim

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r /app/requirements.txt

COPY . /app

EXPOSE 8000

CMD ["fastapi", "dev", "app/main.py", "--port", "8000", "--host", "0.0.0.0"]
